spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/minimums_data
    username: postgres
    password: 210628
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
